import type { AgencyBriefConfig } from './types';

export const bigIdeaConfig: AgencyBriefConfig = {
  type: {
    id: 'big-idea',
    label: 'Big Idea Brief',
    description: 'Ambitious, culturally resonant creative platforms designed for disproportionate impact.',
    icon: 'Lightbulb',
    color: 'purple',
  },
  documentTitle: 'Big Idea Brief',
  questions: [
    {
      id: 'brief_name',
      title: 'Project Name',
      prompt: 'What is the name of this project or platform?',
      placeholder: 'e.g., FY26 Brand Platform Launch, Ramadan Cultural Play...',
      required: true,
    },
    {
      id: 'business_problem',
      title: 'The Business Problem',
      prompt: 'What business challenge are we trying to impact?',
      placeholder: 'e.g., Declining penetration in 18-24 segment, share loss to challenger brand...',
      hint: 'Capture the commercial/business pressure: revenue, share, penetration, perception, growth.',
      required: true,
    },
    {
      id: 'human_problem',
      title: 'The Human Problem',
      prompt: "What is happening in people's lives, behavior or culture that makes this difficult?",
      placeholder: "e.g., The audience's attention is fragmented; the category is invisible to them...",
      hint: 'Look for the human/behavioral/cultural tension behind the business problem.',
      required: true,
    },
    {
      id: 'communication_problem',
      title: 'The Communication Problem',
      prompt: 'What specifically must communication change?',
      placeholder: 'e.g., Shift the perception from utility to identity; make the brand feel essential...',
      hint: 'The single shift in belief, perception, behavior or feeling that comms must drive.',
      required: true,
    },
    {
      id: 'zeitgeist',
      title: 'The Zeitgeist',
      prompt: 'What is happening in culture, society, technology, media behavior, consumer behavior or the category that matters most?',
      placeholder: 'e.g., Cultural movements, platform shifts, category dynamics, audience behaviors that matter now...',
      hint: 'Capture the cultural/societal/technological context the work will enter.',
    },
    {
      id: 'unobvious_truth',
      title: 'The Unobvious Truth',
      prompt: 'What is the reframing truth that unlocks a bigger opportunity? Capture multiple truths if present, and call out the most powerful one.',
      placeholder: 'e.g., Truth 1... Truth 2... Truth 3... Most powerful truth...',
      hint: 'Extract any "Truth 01/02/03" entries and the "Most Powerful Truth" if present.',
      required: true,
    },
    {
      id: 'reframe',
      title: 'The Reframe',
      prompt: 'What is the bigger, more ambitious problem we can solve creatively?',
      placeholder: 'e.g., Not "sell more X", but "redefine what X means in everyday life"...',
      hint: 'A bolder restatement of the problem that opens creative ambition.',
      required: true,
    },
    {
      id: 'big_mission',
      title: 'The Big Mission',
      prompt: 'What are we here to do? Write the strategic mission that creativity must achieve.',
      placeholder: 'e.g., To make X the brand that does Y for Z...',
      hint: 'The strategic mission statement creativity must deliver against.',
      required: true,
    },
    {
      id: 'single_minded_proposition',
      title: 'The Single-Minded Proposition',
      prompt: 'What is the one thing we want people to feel, believe or remember?',
      placeholder: 'e.g., One concise thought the audience should walk away with...',
      hint: 'A single, sharp proposition — feeling, belief or memory.',
      required: true,
    },
    {
      id: 'reasons_to_believe',
      title: 'Reasons to Believe',
      prompt: 'What gives this idea legitimacy? Include product truths, proof points, data, partnerships and brand equities.',
      placeholder: 'e.g., Product features, data points, partnerships, brand heritage, third-party validation...',
      hint: 'Concrete substantiation: product, data, partnerships, equities.',
    },
    {
      id: 'audience',
      title: 'The Audience',
      prompt: 'Go beyond demographics. Include behaviors, motivations, emotional tensions, aspirations and barriers.',
      placeholder: 'e.g., Who they are, what they do, what tensions they live with, what they aspire to...',
      hint: 'Look for behavioral, motivational, emotional and aspirational detail beyond age/income.',
      required: true,
    },
    {
      id: 'tone_feel',
      title: 'What Should This Idea Feel Like?',
      prompt: 'Define the tone, energy and emotional character of the work.',
      placeholder: 'e.g., Confident, optimistic, irreverent, premium, raw, joyful...',
      hint: 'Adjectives, references, energy descriptors that define the emotional character.',
    },
    {
      id: 'no_small_media',
      title: 'No Small Media',
      prompt: 'How could this idea move through the world? Consider moments, momentum, participation and system thinking.',
      placeholder: 'e.g., Cultural moments to enter, participation mechanics, ecosystem opportunities...',
      hint: 'How the idea travels: moments, participation, ecosystem, owned/earned/paid.',
    },
    {
      id: 'what_big_looks_like',
      title: "What Does 'Big' Look Like?",
      prompt: 'Define business KPIs, brand KPIs and cultural KPIs.',
      placeholder: 'e.g., Sales lift, brand consideration, share of voice, earned media, cultural mentions...',
      hint: 'Pull out business, brand and cultural success metrics separately if mentioned.',
      required: true,
    },
    {
      id: 'mandatories',
      title: 'Mandatories',
      prompt: 'Only include what materially affects the creative outcome — deliverables, timing, budget, platforms, legal restrictions.',
      placeholder: 'e.g., Specific deliverables, key dates, budget envelope, platform requirements, legal lines...',
      hint: 'Hard constraints only — deliverables, timing, budget, platforms, legal.',
      allowUpload: true,
    },
  ],
};
