import type { AgencyBriefConfig } from './types';

export const productionConfig: AgencyBriefConfig = {
  type: {
    id: 'production',
    label: 'Production Brief',
    description: 'TV / film production brief covering client servicing details, creative direction and approvals.',
    icon: 'Clapperboard',
    color: 'teal',
  },
  documentTitle: 'TV Production Brief',
  questions: [
    {
      id: 'brief_name',
      title: 'Project Name',
      prompt: 'Project / film name.',
      placeholder: 'e.g., Brand Launch TVC, Ramadan Hero Film...',
      required: true,
    },
    {
      id: 'client',
      title: 'Client',
      prompt: 'Client name.',
      placeholder: 'e.g., Brand X',
      required: true,
    },
    {
      id: 'job_basics',
      title: 'Job Number & Title',
      prompt: 'Job number and working title for this production.',
      placeholder: 'e.g., Job No: 12345, Title: ...',
      hint: 'Internal job number and the working title.',
    },
    {
      id: 'budget',
      title: 'Indicative Budget',
      prompt: 'Indicative production budget.',
      placeholder: 'e.g., AED / USD range, or budget envelope...',
      hint: 'Budget figure or envelope.',
      required: true,
    },
    {
      id: 'airing_details',
      title: 'Airing Details',
      prompt: 'Airing medium(s), region(s), duration, on-air date and delivery date.',
      placeholder: 'e.g., TV + digital, GCC, 60s + cutdowns, on air Mar 1, delivery Feb 15...',
      hint: 'Capture medium, region, duration, on-air date, delivery date.',
      required: true,
    },
    {
      id: 'versions_cutdowns',
      title: 'Versions, Cutdowns & Languages',
      prompt: 'Versions, cutdowns, languages and output formats required.',
      placeholder: 'e.g., 60s / 30s / 15s, English + Arabic, 16:9 + 9:16 + 1:1, master + social cutdowns...',
      hint: 'Number of versions, languages, aspect ratios, shooting format and output.',
      required: true,
    },
    {
      id: 'cast_music_exclusivity',
      title: 'Cast & Music Exclusivity',
      prompt: 'Exclusivity requirements for cast and music.',
      placeholder: 'e.g., 12-month category exclusivity for talent, full buyout for music...',
      hint: 'Talent and music exclusivity window and scope.',
    },
    {
      id: 'adstream_brief',
      title: 'AdstreaM / Trafficking Brief',
      prompt: 'Trafficking details — attach or describe the AdstreaM sheet.',
      placeholder: 'e.g., AdstreaM Excel attached; key trafficking details...',
      hint: 'Trafficking/AdstreaM sheet details.',
      allowUpload: true,
    },
    {
      id: 'client_assets',
      title: 'Assets From Client',
      prompt: 'What will be available from the client? E.g. product packs for the shoot, hero products, brand assets.',
      placeholder: 'e.g., 50 retail packs, hero products, brand fonts, logo files...',
      hint: 'Physical and digital assets the client provides.',
      allowUpload: true,
    },
    {
      id: 'client_servicing_notes',
      title: 'Other Notes — Client Servicing',
      prompt: 'Any additional notes from the client servicing team.',
      placeholder: 'e.g., Stakeholder context, approval nuances, dependencies...',
      hint: 'Catch-all for servicing notes.',
    },
    {
      id: 'script',
      title: 'Script',
      prompt: 'Final script. If there are different scripts per cutdown, include each.',
      placeholder: 'e.g., 60s hero script + 30s cutdown script...',
      hint: 'Full scripts including cutdown variants.',
      allowUpload: true,
      required: true,
    },
    {
      id: 'storyboard',
      title: 'Storyboard',
      prompt: 'Storyboard or link to storyboard.',
      placeholder: 'e.g., Frame-by-frame storyboard description, or link to PDF...',
      hint: 'Storyboard content or link.',
      allowUpload: true,
    },
    {
      id: 'creative_pov',
      title: 'Creative Point of View & Director Brief',
      prompt: 'Creative point of view and director brief, including at least one film reference for each.',
      placeholder: 'e.g., POV summary; director brief; references to films, directors, treatments...',
      hint: 'Creative POV, director-facing brief and film references.',
      allowUpload: true,
      required: true,
    },
    {
      id: 'location_brief',
      title: 'Location Brief',
      prompt: 'Locations required and references.',
      placeholder: 'e.g., Location 1 description and reference; Location 2; etc.',
      hint: 'Locations needed plus visual references.',
    },
    {
      id: 'casting_brief',
      title: 'Casting Brief',
      prompt: 'Casting requirements and references.',
      placeholder: 'e.g., Cast 1 description and reference; Cast 2; etc.',
      hint: 'Cast roles, descriptions and references.',
    },
    {
      id: 'wardrobe',
      title: 'Wardrobe Brief & References',
      prompt: 'Wardrobe brief and references.',
      placeholder: 'e.g., Wardrobe direction per cast member, references...',
      hint: 'Wardrobe direction and references.',
    },
    {
      id: 'food_packaging',
      title: 'Food & Packaging Shots',
      prompt: 'Brief for beauty shots, cutlery and packaging — include style references.',
      placeholder: 'e.g., Beauty shot brief, cutlery style, packaging references...',
      hint: 'Product/food/packaging beauty shot direction and references.',
    },
    {
      id: 'graphics_brief',
      title: 'Graphics Brief — VFX, 2D & 3D',
      prompt: 'VFX, 2D and 3D requirements with references for each.',
      placeholder: 'e.g., VFX brief + 3 references; 2D brief + 3 references; 3D brief + 3 references...',
      hint: 'Separate VFX, 2D and 3D briefs and reference sets.',
    },
    {
      id: 'product_demo',
      title: 'Product Demo Brief',
      prompt: 'Final product demo script and reference images/links.',
      placeholder: 'e.g., Demo script + reference frames or product videos...',
      hint: 'Product demo script and references.',
      allowUpload: true,
    },
    {
      id: 'audio_brief',
      title: 'Audio Brief — VO & Music',
      prompt: 'Voiceover brief with references, and music brief with references.',
      placeholder: 'e.g., VO direction + 5 references; music direction + 5 references...',
      hint: 'Separate VO and music briefs with references.',
    },
    {
      id: 'creative_team_notes',
      title: 'Creative Team — Other Notes & Mandatories',
      prompt: 'Any additional creative-team notes and mandatories.',
      placeholder: 'e.g., Tone watch-outs, brand-side mandatories, restrictions...',
      hint: 'Creative-team notes and hard mandatories.',
    },
    {
      id: 'approvals',
      title: 'Final Approvals',
      prompt: 'Approvals required per element — script (EN/AR), VO (EN/AR), treatment, production-house notes, etc.',
      placeholder: 'e.g., Script EN approved, Script AR pending, VO EN approved, Treatment approved...',
      hint: 'Per-element approval status from the client.',
      required: true,
    },
  ],
};
