import type { AgencyBriefConfig } from './types';

export const socialConfig: AgencyBriefConfig = {
  type: {
    id: 'social',
    label: 'Social Brief',
    description: 'Social-first ideas that are culturally alive, platform-native and impossible to ignore.',
    icon: 'Share2',
    color: 'pink',
  },
  documentTitle: 'Social Brief',
  questions: [
    {
      id: 'brief_name',
      title: 'Project Name',
      prompt: 'What is the name of this social brief?',
      placeholder: 'e.g., Always-On Q2 Social, Launch Social Sprint...',
      required: true,
    },
    {
      id: 'role_of_social',
      title: 'What Are We Trying To Do?',
      prompt: 'Define the role this work plays within the wider campaign or brand ecosystem.',
      placeholder: 'e.g., Launch a campaign, drive conversation, create participation, extend a platform, react to culture, build consistency, create social fame, drive community engagement...',
      hint: 'The role social plays in the bigger picture.',
      required: true,
    },
    {
      id: 'ladder_to_big_idea',
      title: 'How Does This Ladder Into the Big Idea?',
      prompt: 'Connect this brief back to the parent strategic platform. Include the Big Mission, the Reframe, the Single-Minded Proposition and the role social plays within the broader ecosystem.',
      placeholder: 'e.g., Parent platform name, mission, reframe, SMP, role of social...',
      hint: 'Pull through parent platform, mission, reframe, SMP and social\'s ecosystem role.',
      required: true,
    },
    {
      id: 'social_behavior',
      title: 'The Social Behavior We Want To Create',
      prompt: 'The best social ideas change behavior — not just impressions. What behavior should this drive?',
      placeholder: 'e.g., Sharing, commenting, tagging friends, duetting / remixing, saving, meme creation, community participation, creator adoption...',
      hint: 'The specific user behavior the work should generate.',
      required: true,
    },
    {
      id: 'audience',
      title: 'Who Are We Talking To?',
      prompt: 'Focus on mindset, platform behavior and cultural fluency. Include behaviors, subcultures, motivations, social habits, platform usage patterns and emotional tensions.',
      placeholder: 'e.g., Behaviors, subcultures, motivations, social habits, platform usage, tensions...',
      hint: 'Mindset and platform-native behavior over demographics; include subcultures.',
      required: true,
    },
    {
      id: 'culture_now',
      title: 'What Is Happening In Culture Right Now?',
      prompt: 'What conversations, tensions, formats, behaviors, creator trends or platform dynamics matter right now?',
      placeholder: 'e.g., Conversations, tensions, formats, creator trends, platform dynamics...',
      hint: 'Live cultural signals — conversations, trends, formats, creator behaviors.',
    },
    {
      id: 'insight_or_tension',
      title: 'Key Insight or Social Tension',
      prompt: 'What truth or behavior should this social work tap into?',
      placeholder: 'e.g., The social tension between X and Y that the audience lives with online...',
      hint: 'A sharp social or human truth/tension the work should activate.',
      required: true,
    },
    {
      id: 'tone_feel',
      title: 'What Should This Feel Like?',
      prompt: 'Define the tone, energy and personality of the work.',
      placeholder: 'e.g., Unignorable, fast-moving, native to platform, playful, premium, chaotic, sharp, human...',
      hint: 'Tone, energy, personality adjectives.',
    },
    {
      id: 'creative_territories',
      title: 'Creative Territories & Content Springboards',
      prompt: 'Provide useful creative provocations and directions.',
      placeholder: 'e.g., Creator collaborations, reactive formats, meme behavior, POV formats, community mechanics, conversation hooks, trend adaptations, series structures...',
      hint: 'Provocations and territories — not finished executions.',
    },
    {
      id: 'platform_format',
      title: 'Platform & Format Strategy',
      prompt: 'How should this adapt across platforms? Consider TikTok, Instagram, YouTube Shorts, X / realtime culture, LinkedIn, Snapchat and creator ecosystems.',
      placeholder: 'e.g., Per-platform behavior, formats, ratios, native expectations...',
      hint: 'Per-platform approach — formats, behaviors, native expectations.',
      required: true,
    },
    {
      id: 'reactive_always_on',
      title: 'Reactive & Always-On Opportunities',
      prompt: 'What live moments, events, behaviors or conversations should the team actively monitor and respond to?',
      placeholder: 'e.g., Cultural moments, events, ongoing conversations to react to...',
      hint: 'Live moments and conversations to monitor.',
    },
    {
      id: 'deliverables',
      title: 'Deliverables',
      prompt: 'Clearly define volume, formats, ratios, durations, static/motion/stories/reels, shoot and editing requirements.',
      placeholder: 'e.g., Volume, formats, ratios, durations, shoot/edit needs...',
      hint: 'Volume + format breakdown including production needs.',
      allowUpload: true,
      required: true,
    },
    {
      id: 'assets_references',
      title: 'Assets & References',
      prompt: 'Include storyboard links, visual references, creator references, music references, existing brand assets, fonts/design systems and previous social learnings.',
      placeholder: 'e.g., Reference links, brand assets, fonts, prior learnings...',
      hint: 'References, assets, fonts, prior learnings.',
      allowUpload: true,
    },
    {
      id: 'mandatories',
      title: 'Mandatories & Watch-Outs',
      prompt: 'Mandatories and things to avoid.',
      placeholder: 'e.g., Logos, CTAs, outro frames, legal lines, platform restrictions, cultural sensitivities, topics to avoid...',
      hint: 'Hard constraints AND topics/treatments to avoid.',
      allowUpload: true,
    },
    {
      id: 'success_metrics',
      title: 'Success Metrics',
      prompt: 'Measure beyond reach.',
      placeholder: 'e.g., Engagement rate, shares, saves, comments, watch time, conversation volume, sentiment, UGC creation, creator adoption, earned media...',
      hint: 'Specific, social-native KPIs beyond reach/impressions.',
      required: true,
    },
  ],
};
