import type { AgencyBriefConfig } from './types';

export const taskConfig: AgencyBriefConfig = {
  type: {
    id: 'task',
    label: 'Task Brief',
    description: 'Translate the Big Idea platform into focused, executional assignments that still feel creatively ambitious.',
    icon: 'Zap',
    color: 'orange',
  },
  documentTitle: 'Task Brief',
  questions: [
    {
      id: 'brief_name',
      title: 'Project Name',
      prompt: 'What is the name of this task or assignment?',
      placeholder: 'e.g., Q1 Social Content Series, OOH Adaptation for Launch...',
      required: true,
    },
    {
      id: 'what_are_we_making',
      title: 'What Are We Making?',
      prompt: 'Clearly define the assignment.',
      placeholder: 'e.g., Social content series, tactical retail campaign, launch film, OOH adaptation, CRM journey, influencer toolkit, activation mechanic...',
      hint: 'The concrete output type and scope of work.',
      required: true,
    },
    {
      id: 'ladder_to_big_idea',
      title: 'How Does This Ladder Into the Big Idea?',
      prompt: 'What is the parent campaign, platform or strategic mission this work supports? Include the Big Mission, the Reframe, the Single-Minded Proposition and the role this task plays within the ecosystem.',
      placeholder: "e.g., Parent platform name, the mission it serves, the SMP it expresses, this task's role...",
      hint: 'Pull through the parent platform, mission, reframe, SMP and the role of this task.',
      required: true,
    },
    {
      id: 'communication_objective',
      title: 'Specific Communication Objective',
      prompt: 'What exactly must this piece of work achieve?',
      placeholder: 'e.g., Drive urgency, build awareness, create participation, shift perception, explain utility, drive trial, generate conversation...',
      hint: 'A single, measurable communications objective for this specific piece of work.',
      required: true,
    },
    {
      id: 'audience',
      title: 'Who Are We Talking To?',
      prompt: 'Focus on behaviors and mindset over demographics. Include current mindset, motivations, barriers and desired emotional response.',
      placeholder: 'e.g., Behaviors, mindset, motivations, barriers, the emotional shift we want...',
      hint: 'Behavioral and emotional detail — current mindset, motivations, barriers, desired response.',
      required: true,
    },
    {
      id: 'insight_or_tension',
      title: 'Key Insight or Tension',
      prompt: 'What human truth, behavior or cultural tension should this execution tap into?',
      placeholder: 'e.g., The tension between X and Y in the audience\'s life...',
      hint: 'A sharp human or cultural truth/tension the work should activate.',
      required: true,
    },
    {
      id: 'desired_action',
      title: 'What Should People Do?',
      prompt: 'Define the desired action or behavior.',
      placeholder: 'e.g., Click, share, visit, register, purchase, create content, talk about the brand...',
      hint: 'A concrete action or behavior the audience should take.',
      required: true,
    },
    {
      id: 'tone_feel',
      title: 'What Should This Feel Like?',
      prompt: 'Define the tone, energy and emotional character of the work.',
      placeholder: 'e.g., Playful, premium, provocative, optimistic, unignorable, culturally fluent...',
      hint: 'Tone, energy, personality adjectives.',
    },
    {
      id: 'creative_springboards',
      title: 'Creative Springboards',
      prompt: 'Useful provocations, references or directional cues. Not executions. Not scripts. Stimulus that helps creatives unlock stronger thinking.',
      placeholder: 'e.g., References, provocations, cultural cues, formats to explore...',
      hint: 'Provocations and references — not executions.',
    },
    {
      id: 'channel_context',
      title: 'Channel & Context',
      prompt: 'Where will this appear and what is the audience mindset in that environment? Consider platform behavior, viewing context, attention span, creator ecosystem and cultural timing.',
      placeholder: 'e.g., Platform, viewing context, attention span, creator ecosystem, cultural timing...',
      hint: 'Channels, platform mindset, viewing context and cultural timing.',
    },
    {
      id: 'deliverables',
      title: 'Deliverables',
      prompt: 'List all required deliverables and specifications.',
      placeholder: 'e.g., Formats, ratios, durations, languages, versions, cutdowns...',
      hint: 'Specific deliverables and their specs.',
      allowUpload: true,
      required: true,
    },
    {
      id: 'timing_milestones',
      title: 'Timing & Milestones',
      prompt: 'Include internal review dates, client presentation dates, production timelines, launch dates and market/event timing.',
      placeholder: 'e.g., Key dates, reviews, production milestones, on-air date...',
      hint: 'Concrete dates and milestones; reviews, presentations, production, launch.',
      required: true,
    },
    {
      id: 'success_metrics',
      title: 'Success Metrics',
      prompt: 'Define how success will be measured.',
      placeholder: 'e.g., Engagement, CTR, video completion, traffic, sales uplift, participation, PR pickup, sentiment...',
      hint: 'Quantitative and qualitative success metrics.',
      required: true,
    },
    {
      id: 'mandatories',
      title: 'Mandatories',
      prompt: 'Only include what materially impacts the creative outcome.',
      placeholder: 'e.g., Brand guidelines, legal lines, mandatory assets, language requirements, visual restrictions, media specs...',
      hint: 'Hard constraints only.',
      allowUpload: true,
    },
  ],
};
