-- Users: the allowlist and the identity (Supabase / Postgres).
-- Run once in the Supabase SQL editor, BEFORE the data migration.
--
-- This replaces the Microsoft SQL Server `bbdo_users` table. Users and briefs now live in
-- one database, which finally allows a real foreign key between them (added in 0004, once
-- the rows exist).
--
-- Ids are deliberately the ORIGINAL integers carried over from SQL Server, not new ones:
-- `briefs.user_id` points at them, and `session.userId` carries them in the JWT. Preserving
-- them means no brief is orphaned and no one is signed out.

create table if not exists bbdo_users (
  -- No `generated by default as identity` here: rows arrive with explicit ids from the
  -- migration. The sequence is attached afterwards in 0004 and set past the highest id.
  id         integer     primary key,
  email      text        not null unique,

  -- `is_active` is the COMPLETE definition of "may sign in" — with OTP login there is no
  -- password and no second gate. Defaults to false so a new row is locked out until
  -- somebody explicitly activates it (matches the old BIT NOT NULL DEFAULT 0).
  is_active  boolean     not null default false,

  created_at timestamptz not null default now()
);

-- Unique on lower(email), not merely indexed.
--
-- SQL Server's NVARCHAR compared case-insensitively under the default collation; Postgres
-- `text` does not. Without this, 'Jane@omc.com' and 'jane@omc.com' could both exist and a
-- lookup would silently miss — and because the OTP request route deliberately returns an
-- identical response for unknown addresses, that user would see "we've sent a code" and
-- simply never receive one. No error, nothing to debug. This makes that state impossible.
create unique index if not exists bbdo_users_email_lower_idx on bbdo_users (lower(email));

-- Same backstop as `briefs` and `otp_attempts`: every read and write goes through the
-- service-role key from our own server code, which bypasses RLS. Enabling it with no
-- policies means a leaked anon/publishable key reaches nothing here.
alter table bbdo_users enable row level security;
